### ISSUE TITLE
Feature request: Expanding query support

### ISSUE THREAD

**Issue by B-Reif** [bcarruthers/garnet#10]
Currently, as the README states, only a certain set of joins are supported. I'm interested in constructing queries with a filter based on the values of the shared components. What kinds of query operators are on the roadmap? What would it take to support filter values? I'd be happy to put together a PR for this.

**Comment by bcarruthers** [comment]
Hi B-Reif,

If that's a common use case for you, you could define a custom query on top of an existing one:

```
module Join =
    /// Iterate over all entities matching a value
    let iterValue<'a, 'b when 'a : equality> (matchValue : 'a) action =
        fun param struct(a : 'a, b : 'b) ->
            if a = matchValue then
                action a b
        |> Join.iter2
```

And when you wanted to use it:

```
let iterLowEnergy =
    fun param struct(e : Energy, eid : Eid) ->
        // do something here
        ()
    |> Join.iterValue { energy = 1 }
    |> Join.over c
```

My approach so far has been to go with a predefined set of queries that covered most of my needs, then supplement those with custom queries or work around the limitations. Writing a custom query means copying and modifying existing iteration code, or just building on top of an existing one like the above code.

Regarding criteria for including a query in the library, so far I've left out all but the simplest variations to avoid a combinatorial explosion of query definitions (since they're all basically hardcoded). So I'd hesitate to add a set of equality queries to the library until the overall query design was revisited.

My ideal query system would be:
- Fast to iterate
- No allocations
- Statically-typed
- Simple syntax, including no redundant type annotations
- Optional qualifiers on params, such as mutability
- Composing arbitrary expressions instead of a predefined set
- Similarly usable from C#
- Minimal code duplication
- Maybe a 'foreach' syntax if it doesn't impact performance

It's not possible to achieve all those in F# or C#, so they'd need to be prioritized.

Please let me know if you have any suggestions or specific scenarios to support!

**Comment by B-Reif** [comment]
I'm using Garnet to explore porting my existing MVU-style game to an ECS architecture, so I'm just beginning to learn these concepts. That kind of extension is basically what I had in mind. I was initially guessing I would use a predicate function (rather than a match value) but I suppose that would allocate closures. I don't think I'm qualified to really comment on the direction of something like this yet.

Unity's ECS architecture currently has a [filter API](https://docs.unity3d.com/Packages/com.unity.entities@0.0/manual/component_group.html#defining-filters:~:text=Defining%20filters,you%20can%20also%20filter%20the%20view.) that enables some filters based on some exact component values, which looks pretty similar to your suggestion here.

Edit: the API I had in mind looked something like
```
fun e struct(energy: Energy, eid: Eid) ->
    // do something
    ()
|> Where.where2 (fun e struct(energy: Energy, eid: Eid) -> energy > 0)
|> Join.iter2
|> Join.over(myContainer)
```

**Comment by bcarruthers** [comment]
Got it, how about this then:
```
module Join =
    let where predicate action =
        fun param values ->
            if predicate param values then
                action param values
```
Test:
```
let c = Container()
let update =
    fun param struct(e : int, eid : Eid) ->
        // do something here
        printfn "%A %A" eid e
    |> Join.where (fun param struct(e, _) -> e > 10)
    |> Join.iter2
    |> Join.over c
c.Create().Add(1)
c.Create().Add(20)
c.Commit()
update()
```
Since that approach is fairly generic, it may be useful to include in the library. And I don't believe it would be incurring any allocations per-call.

**Comment by B-Reif** [comment]
Added this PR #12 ⬆️ to this specification.
