### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by B-Reif** [bcarruthers/garnet#11]
I've been studying the codebase some to learn more about its internals. I'd like to document some of the functionality as I learn about it. Would you review/accept PRs for docs? Do you have any preferences for how elements are documented? I was considering adding XML docs to individual elements and then maybe compiling them with a tool like [FSharp.Formatting](https://fsprojects.github.io/FSharp.Formatting).

**Comment by bcarruthers** [comment]
I like the approach of documenting as you learn something. Let me know if anything seems strange or doesn't make sense!

I imagine docs could go something like this:
1. Add FSharp.Formatting dependency and build step
2. Generate the doc html files and check in to a new docs branch (?)
3. Point GitHub to the docs branch and access via http://bcarruthers.github.io/garnet

And then every time we add comments, the build output would be checked in to the docs branch. I'm open to other suggestions if you have experience with this.

I'd be happy to review any PRs you come up with, although I'd suggest something minimal to begin with. We may want to start with non-obvious method or type comments rather than parameter-level, except for common or confusing cases.
