### ISSUE TITLE
Make separate repos?

### ISSUE THREAD

**Issue by jhorv** [bcarruthers/garnet#15]
I’m experimenting with Garnet and Garnet.Toolkit alongside other libs like [Spectre.Console](https://spectreconsole.net) and MonoGame, but Toolkit’s Veldrid dependency is a little cumbersome.

I’ve also found that Toolkit needs tweaks to work on Linux (in Rider) and macOS (in VS for Mac). I think there are benefits to having core, platform-independent Garnet be separate from code that might be fiddled with more frequently, like platform-sensitive or Veldrid-dependent extras (Toolkit) and Samples.

What do you think of splitting things into their own repos? I propose one each for Garnet, Toolkit, Toolkit.Veldrid, and Samples.

**Comment by bcarruthers** [comment]
Sorry for the late reply! Yes, that approach and split makes sense, and the main reason I haven't done that is for the convenience of working with a single repo, keeping everything in sync and building, and the original intent that the toolkit was just a support library for the samples.

I guess the cumbersome part is that the core Garnet library has zero dependencies, but you end up pulling all these other graphics/audio/etc dependencies to build the main sln simply because the sample projects and toolkit use them. Another possible split could be two repos, Garnet and Garnet.Toolkit, with samples and Veldrid included in the latter for the time being.
