### ISSUE TITLE
Showcase perf gains

### ISSUE THREAD

**Issue by jwosty** [bcarruthers/garnet#21]
Hello!

This library is really intriguing and the samples are doing a great job demonstrating real-world uses. Thank you for putting this out into the world. The world needs for first-class F# game tech.

I would really really love to see a version of one or more of these samples reimplemented with identical behavior, but instead using a traditional FP approach (perhaps MVU/Elmish arch), so I can compare the performance differences. It would go a long way in helping better understand the tradeoffs of choosing such an approach.

**Comment by bcarruthers** [comment]
Glad the library is of interest to you!

I've tried those approaches in the past, and they seemed fine for smaller games or applications that weren't so demanding of real-time performance. But as the volume of data changing scales up (like increased frame rate with lots of dynamic entities), performance differences can become more pronounced.

If I recall, a simple prototype with flocking logic suffered less than a 2x penalty by not mutating data in place, but it wasn't noticeable because it was still much faster than 60 FPS. For a typical turn-based classic roguelike, it probably wouldn't matter. For a game with a larger scale, the performance differences and allocation might add up and eventually lead to GC stutters etc.

**Comment by bcarruthers** [comment]
I don't plan to update the library further for the time being, but it hopefully it's still useful as a reference.
